language: cpp

matrix:
  include:

    - os: linux
      sudo: true
      compiler: gcc
      install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update
        - sudo apt-get install g++-4.8 zlib1g-dev
      script:
        - make -j
        - ./run.sh
        - make -C tests

    - os: osx
      compiler: clang-3.7
      script:
        - make -j
        - ./run.sh
        - make -C tests

