language: cpp

cache:
  apt: true

matrix:
  include:

    - os: linux 
      compiler: gcc5
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['g++-5', 'cmake', 'cmake-data', 'libboost-dev']
      install:
        - export CXX="g++-5" CC="gcc-5"

    - os: osx
      compiler: clang-3.7
      before_install:
        - sudo brew update
        - sudo brew tap homebrew/versions
        - sudo brew install llvm37
        - sudo brew install boost155
        - sudo brew unlink cmake && sudo brew install cmake31
        - sudo pip install --upgrade jinja2 nose
      install:
        - export CXX="clang++-3.7" CC="clang-3.7"

script:
  - cmake . && make && ./run.sh
